bmw_club_bg/common/urls.py
from django.urls import path, include

from bmw_club_bg.common.views import UserPostListView, like_post, PostDetailView, add_comment, \
    CreatePostView, EditPostView, DeletePostView

urlpatterns = [
    path('', UserPostListView.as_view(), name='home'),
    path('like_post/<int:pk>/<str:action>/', like_post, name='like_post'),
    path('post/', include([
        path('<int:pk>/', PostDetailView.as_view(), name='details_post'),
        path('add/', CreatePostView.as_view(), name='add_post'),
        path('edit/<int:pk>/', EditPostView.as_view(), name='edit_post'),
        path('delete/<int:pk>/', DeletePostView.as_view(), name='delete_post'),
        path('<int:pk>/comment/', add_comment, name='add_comment'),

    ])),


]

bmw_club_bg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('bmw_club_bg.common.urls')),
    path('authentication/', include('bmw_club_bg.accounts.urls')),
    path('groups/', include('bmw_club_bg.groups.urls')),
    path('profile/', include('bmw_club_bg.profiles.urls')),
    path('notifications/', include('bmw_club_bg.notifications.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bmw_club_bg/common/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='authored_posts')
    content = models.TextField()
    image_url = models.URLField()
    location = models.CharField(max_length=20, validators=[MinLengthValidator(2)])
    comments = models.ManyToManyField(User, through='Comment', related_name='commented_posts')
    likes = models.ManyToManyField(User, related_name='liked_posts')
    date = models.DateField(auto_now_add=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

bmw_club_bg/common/forms.py
from django import forms
from django.http import request

from bmw_club_bg.common.models import Comment, Post
from bmw_club_bg.groups.models import Group


class BasePostForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=None)

    class Meta:
        model = Post
        fields = ['content', 'location', 'image_url', 'group']
        labels = {
            'content': "What's revving on your mind?",
            'location': 'Where?',
            'image_url': 'Image URL:',
            'group': 'Choose a Group',
        }
        widgets = {
            'content': forms.Textarea(attrs={'rows': 6}),  # Set the number of rows for the textarea
        }


class CreatePostForm(BasePostForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(users=user)

bmw_club_bg/common/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse, request
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from bmw_club_bg.common.forms import CreatePostForm
from bmw_club_bg.common.models import Post, Comment
from bmw_club_bg.notifications.models import Notification


class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'common/home-page.html'

    def get_queryset(self):
        user = self.request.user
        search_query = self.request.GET.get('search_query', None)

        if search_query:
            queryset = Post.objects.filter(author__username__icontains=search_query, groups__users=user).order_by(
                '-date')
        else:
            queryset = Post.objects.filter(groups__users=user).order_by('-date')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        liked_posts = []
        user = self.request.user


        if user.is_authenticated:
            liked_posts = user.liked_posts.all()
        context['liked_posts'] = liked_posts

        # Add post URLs to the context
        for post in context['object_list']:
            post_url = self.request.build_absolute_uri(reverse('details_post', args=[post.pk]))
            post.post_url = post_url

        return context



@login_required
def like_post(request, pk, action):
    post = get_object_or_404(Post, id=pk)
    if action == 'like':
        post.likes.add(request.user)
    elif action == 'dislike':
        post.likes.remove(request.user)
    else:
        return JsonResponse({'success': False})

    if request.user != post.author:  # Avoid sending notification if the user liked their own post
        notification_content = f"liked your post: {post.content}"
        notification = Notification(user=post.author, user_like=request.user, content=notification_content)
        notification.save()

    return JsonResponse({'success': True, 'action': action})


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'posts/post-details-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        liked_posts = []
        user = self.request.user
        if user.is_authenticated:
            liked_posts = user.liked_posts.all()
        context['liked_posts'] = liked_posts
        context['now_user'] = user
        context['group_chef'] = self.object.groups.first().created_by

        return context



@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        try:
            data = json.loads(request.body)  # Parse the JSON data
            comment_text = data.get('comment')  # Get the comment from the JSON data
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)

        if not comment_text:
            return JsonResponse({'error': 'Comment is empty'}, status=400)

        # Save the comment to the database
        comment = Comment(user=request.user, post=post, comment=comment_text)
        comment.save()

        # Return the new comment data as JSON
        return JsonResponse({
            'user': {
                'username': comment.user.username,
                'profile': {
                    'first_name': comment.user.profile.first_name,
                    'last_name': comment.user.profile.last_name,
                    'image': comment.user.profile.image.url if comment.user.profile.image else None,
                    # Include other profile attributes as needed...
                }},

            'comment': comment.comment,
            'timestamp': comment.timestamp.strftime('%Y-%m-%d %H:%M:%S')
        })

    # Return an empty JSON response for non-POST requests
    return JsonResponse({})

class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreatePostForm
    template_name = 'posts/post-add-page.html'

    def get_success_url(self):
        # Redirect to the details page of the newly created post
        return reverse('details_post', args=[self.object.pk])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save(commit=False)  # Save the form data without committing to the database
        post.save()  # Save the post to generate the post ID

        group_data = form.cleaned_data.get('group')
        post.groups.set([group_data])

        return super().form_valid(form)


class EditPostView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'posts/post-edit-page.html'
    context_object_name = 'post'
    fields = ['content', 'location', 'image_url']

    def get_success_url(self):
        # Redirect to the details page of the newly updated post
        return reverse('details_post', args=[self.object.pk])

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        if post.author != self.request.user:
            # If the user is not the author of the post, return a 404 error
            raise Http404
        return post

    def form_valid(self, form):
        response = super().form_valid(form)
        # Perform any additional actions after the form is successfully validated
        return response


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/post-delete-page.html'
    success_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        if post.author != self.request.user and self.request.user != post.groups.first().created_by:
            raise Http404("You are not allowed to delete this post.")
        return post

bmw_club_bg/common/templates/posts/post-add-page.html
{% extends 'base.html' %}
{% block content %}
<main>
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Create Post</h2>
        <!-- Start Add Photo Form -->
        <form  method="post" action="" enctype="multipart/form-data">


            {{ form.as_p }}
            {% csrf_token %}

            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Create</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
</main>
{% endblock %}

bmw_club_bg/common/templates/posts/post-delete-page.html
{% extends 'base.html' %}
{% block content %}
    <main>

        <!-- Starts Edit Photo Section -->
        <div class="edit-delete edit-photo">
            <h2>Delete post</h2>

            <!-- Starts Edit Photo Form -->
            <form action="{% url 'delete_post' post.pk %}" method="post">
                <p>
                    <label for="id_content">Content:</label>
                    <textarea name="content" cols="40" rows="10" id="id_content" disabled>{{ object.content }}</textarea>


                </p>
                <p>
                    <label for="id_location">Location:</label>
                    <input type="text" name="location" value="{{ object.location }}" maxlength="20" id="id_location" disabled>


                </p>
                <p>
                    <label for="id_image_url">Image url:</label>
                    <input type="url" name="image_url" value="{{ object.image_url }}" maxlength="200" required=""
                           id="id_image_url" disabled>


                </p>
                {% csrf_token %}
                <button class="edit-btn" type="submit">Delete Post</button>
            </form>
            <!-- End Edit Photo Form -->

        </div>
        <!-- End Edit Photo Section -->

    </main>
{% endblock %}

bmw_club_bg/common/templates/posts/post-details-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="container">
            <div class="col-9">

                <!-- Start Pet Photo Post Section -->


                <div class="card" id="{{ post.id }}">

                    <!-- Start User Details and Image Location -->
                    <div class="top">
                        <div class="userDetails">
                            <!-- Link to User Profile Page -->
                            <a href="#">
                                <div class="profilepic">
                                    <div class="profile_img">
                                        <div class="image">
                                            {% if post.author.profile.image %}
                                                <img src="/media/{{ post.author.profile.image }}" alt="img8">
                                            {% else %}
                                                <img src="{% static 'images/person.png' %}" alt="img8">
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <h3>
                                <!-- Link to User Profile Page -->
                                <a href="#">
                                    {% if post.author.first_name and post.author.last_name %}
                                        {{ post.author.first_name }} {{ post.author.last_name }}
                                    {% else %}
                                        {{ post.author.username }}
                                    {% endif %}
                                </a>
                                <br>
                                <!-- if the photo has location -->
                                <a href="#">@{{ post.author.username }}</a>
                                <span>{{ post.location }}</span>
                                <!-- Date of Publication -->
                                <h5 class="postTime">{{ post.date|date:"d/m/Y" }}</h5>

                            </h3>
                            {% if post.author == now_user or group_chef == now_user%}


                                <div class="edit-delete-btns">
                                {% if post.author == now_user %}
                                    <a href="{% url 'edit_post' object.pk %}">
                                        <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                             alt="edit button">
                                    </a>
                                {% endif %}
                                    <a href="{% url 'delete_post' object.pk %}">
                                        <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}"
                                             alt="bin button">
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <!-- End User Details and Image Location -->
                    <!-- Photo description -->
                    <div class="decription">
                        <p class="pet-details">{{ object.content }}</p>
                        {% for group in object.groups.all %}
                            <a href="#">
                                <p class="message">
                                    <b>#{{ group.name }}</b>

                                </p>
                            </a>
                        {% endfor %}

                    </div>

                    <div class="imgBx" id="place the id of the photo here">
                        <img src="{{ object.image_url }}" alt="post" class="cover">
                    </div>

                    <!-- Start Like and Share Buttons -->
                    <div class="bottom">
                        <div class="actionBtns">
                            <div class="left">
                                <!-- Start Like Button -->
                                <span class="heart like-container" data-post-id="{{ object.pk }}">
                                            <button class="like-button" data-post-id="{{ object.pk }}"
                                                    data-action="{% if object in user.liked_posts.all %}dislike{% else %}like{% endif %}"
                                                    style="background-color: transparent; border: none;">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                     fill="currentColor"
                                                     class="bi {% if object in user.liked_posts.all %}bi-heart-fill{% else %}bi-heart{% endif %}"
                                                     viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd " id="heart-icon{{ object.id }}"
                                                          d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                          fill="{% if object in user.liked_posts.all %}red{% else %}black{% endif %}">

                                                    </path>
                                                </svg>
                                            </button>
                                    </span>

                                <a onclick="copyToClipboard('{{ request.META.HTTP_REFERER }}#{{ post.pk }}')" >
                                    <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                         height="24" role="img" viewBox="0 0 48 48" width="24">
                                        <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                        </path>
                                    </svg>
                                </a>
                                <a>
                                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 512 512">
                                        <path d="M123.6 391.3c12.9-9.4 29.6-11.8 44.6-6.4c26.5 9.6 56.2 15.1 87.8 15.1c124.7 0 208-80.5 208-160s-83.3-160-208-160S48 160.5 48 240c0 32 12.4 62.8 35.7 89.2c8.6 9.7 12.8 22.5 11.8 35.5c-1.4 18.1-5.7 34.7-11.3 49.4c17-7.9 31.1-16.7 39.4-22.7zM21.2 431.9c1.8-2.7 3.5-5.4 5.1-8.1c10-16.6 19.5-38.4 21.4-62.9C17.7 326.8 0 285.1 0 240C0 125.1 114.6 32 256 32s256 93.1 256 208s-114.6 208-256 208c-37.1 0-72.3-6.4-104.1-17.9c-11.9 8.7-31.3 20.6-54.3 30.6c-15.1 6.6-32.3 12.6-50.1 16.1c-.8 .2-1.6 .3-2.4 .5c-4.4 .8-8.7 1.5-13.2 1.9c-.2 0-.5 .1-.7 .1c-5.1 .5-10.2 .8-15.3 .8c-6.5 0-12.3-3.9-14.8-9.9c-2.5-6-1.1-12.8 3.4-17.4c4.1-4.2 7.8-8.7 11.3-13.5c1.7-2.3 3.3-4.6 4.8-6.9c.1-.2 .2-.3 .3-.5z"/>
                                    </svg>
                                </a>

                            </div>
                        </div>
                        <!-- End Like and Share Buttons -->

                        <!-- Number of Likes per Photo -->
                        <div class="comment-like-info">
                            <p class="likes"><strong id="numLike{{ post.pk }}">{{ post.likes.count }}</strong> likes
                            </p>
                            <p class="likes"><strong>{{ post.comments.count }}</strong> comments</p>
                        </div>

                        <div id="commentsContainer">
                            {% for comment_object in object.comment_set.all %}
                                <div class="comments" id="comment{{ comment_object.pk }}">
                                    <div class="top">
                                        <div class="userDetails">
                                            <div class="comment-data">
                                                <div class="profilepic">
                                                    <div class="profile_img">
                                                        <div class="image">
                                                            <!-- User Profile Image -->
                                                            <a href="{% url 'details_profile' username=comment_object.user.username %}">
                                                                {% if comment_object.user.profile.image %}
                                                                    <img src="/media/{{ comment_object.user.profile.image }}"
                                                                         alt="img8">
                                                                {% else %}
                                                                    <img src="{% static 'images/person.png' %}"
                                                                         alt="img8">
                                                                {% endif %}
                                                            </a>

                                                        </div>
                                                    </div>
                                                </div>
                                                <p>
                                                    <!-- Link to User Profile Details Page-->
                                                    <!-- User First and/or Last Name or username-->
                                                    <a href="{% url 'details_profile' username=comment_object.user.username %}"
                                                       style="font-weight: bold ">
                                                        {% if  comment_object.user.profile.first_name and comment_object.user.profile.last_name %}
                                                            {{ comment_object.user.profile.first_name }}
                                                            {{ comment_object.user.profile.last_name }}
                                                        {% else %}
                                                            {{ comment_object.user.username }}
                                                        {% endif %}
                                                    </a>
                                                    <!-- User Comment -->
                                                    {{ comment_object.comment }}
                                                </p>
                                            </div>
                                            <span>{{ comment_object.timestamp|timesince }} ago</span>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Comments Section -->
                            {% endfor %}

                        </div>
                    </div>

                    <!-- Start Add Comments Section -->
                    <div class="addComments">
                        <div class="reaction">
                            <h3>
                                <i class="far fa-smile"></i>
                            </h3>
                        </div>

                        <!-- Start Add Comments Form -->
                        <form id="commentForm" data-url="{% url 'add_comment' object.pk %}">
                            {% csrf_token %}
                            <textarea name="comment" id="commentInput" placeholder="Your comment" required></textarea>
                            <button id="postCommentButton">Post</button>
                        </form>
                        <!-- End Add Comments Form -->

                    </div>
                    <!-- End Add Comments Section -->

                </div>

            </div>
        </div>

    </main>

    <script src={% static 'base-js/copy-to-click-board.js' %}></script>
    <script src={% static 'base-js/like-and-unlike-button.js' %}></script>
    <script src={% static 'base-js/comment-functionality.js' %}></script>

{% endblock %}

bmw_club_bg/common/templates/posts/post-edit-page.html
{% extends 'base.html' %}
{% block content %}
<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit Post</h2>

        <!-- Starts Edit Photo Form -->
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}

            <button class="edit-btn" type="submit">Edit Post</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
{% endblock %}